[package]
name = "atrinik-protocol-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atrinik-actions.workspace = true
atrinik-protocol.workspace = true
atrinik-session.workspace = true
sha2.workspace = true
x509-cert.workspace = true
zeroize.workspace = true

[lints]
workspace = true
