[package]
name = "atrinik-directory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atrinik-protocol-adapter.workspace = true
httpdate.workspace = true
sha2.workspace = true
ureq.workspace = true

[lints]
workspace = true
